# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import res

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 515)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(698, 515))
        MainWindow.setMaximumSize(QtCore.QSize(698, 515))
        MainWindow.setStyleSheet("/* MAIN */\n"
"QWidget {\n"
"    font-family: \'ITC Kabel Std Book\';\n"
"    font-weight: bold;\n"
"    font-size: 20pt;\n"
"    color: #0949ab;\n"
"}\n"
"QWidget[objectName^=\"centralwidget\"] {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #eeeeee;\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove { \n"
"    background-color: rgb(237, 238, 238);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"QSlider::groove:horizontal { \n"
"    height: 16px; \n"
"}\n"
"QSlider::groove:vertical { \n"
"    width: 16px; \n"
"}\n"
"QSlider::handle { \n"
"    background-color: qradialgradient(\n"
"    cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, \n"
"    stop: 0.3 #ffffff, stop: 0.7 #d8e2e8, stop: 0.9 #e8e9ee, stop: 1 #dddddd\n"
");\n"
"    border: none; \n"
"    border-radius: 24px; \n"
"}\n"
"QSlider::handle:horizontal { \n"
"    width: 48px; \n"
"    margin-top: -16px; \n"
"    margin-bottom: -16px; \n"
"}\n"
"QSlider::handle:vertical { \n"
"    height: 48px; \n"
"    margin-left: -16px; \n"
"    margin-right: -16px; \n"
"}\n"
"QSlider::handle:hover { \n"
"    background-color: qradialgradient(\n"
"    cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, \n"
"    stop: 0.3 #e8ffa2, stop: 0.7 #84cb47, stop: 0.9 #9dcb80, stop: 1 #dddddd\n"
");\n"
"}\n"
"QSlider::handle:pressed { \n"
"    background-color: qradialgradient(\n"
"    cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, \n"
"    stop: 0.3 #73df20, stop: 0.7 #47a53b, stop: 0.9 #77c26e, stop: 1 #dddddd\n"
");\n"
"}\n"
"\n"
"/* BUTTONS */\n"
"QPushButton {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #fdfdfd, stop: 1 #dddddd\n"
"    );\n"
"    color: #0949ab;\n"
"    border-radius: 25px;\n"
"    border: none;\n"
"    height: 20px;\n"
"    width: 200px;\n"
"    padding-top: 6px;\n"
"            }\n"
"QPushButton:hover {\n"
"    color: #2cac3a;\n"
"            }\n"
"QPushButton:pressed {\n"
"    background: #e5e5e5;\n"
"            }\n"
"\n"
"/* SPECIAL BUTTONS */\n"
"QPushButton[objectName^=\"closeButton\"] {\n"
"    image: url(:/ui/cross.png);\n"
"}\n"
"QPushButton[objectName^=\"closeButton\"]:hover {\n"
"    image: url(:/ui/cross2.png);\n"
"}\n"
"QPushButton[objectName^=\"minusButton\"] {\n"
"    image: url(:/ui/minus.png);\n"
"}\n"
"QPushButton[objectName^=\"minusButton\"]:hover {\n"
"    image: url(:/ui/minus2.png);\n"
"}\n"
"QPushButton[objectName^=\"closeButton\"],QPushButton[objectName^=\"minusButton\"] {\n"
"    border-radius: 15px;\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    text-align: center;\n"
"    padding: 0;\n"
"}\n"
"\n"
"QPushButton[objectName^=\"refreshButton\"] {\n"
"    image: url(:/ui/refresh.png);\n"
"    padding: 0;\n"
"}\n"
"QPushButton[objectName^=\"refreshButton\"]:hover {\n"
"    image: url(:/ui/refresh2.png);\n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #fdfdfd, stop: 1 #dddddd\n"
"    );\n"
"    color: #0949ab;\n"
"    border-radius: 8px;\n"
"    border: none;\n"
"    height: 20px;\n"
"    width: 200px;\n"
"    padding: 6px 18px 1px 10px;\n"
"}\n"
"/*QComboBox:hover {\n"
"    color: #2cac3a;\n"
"}*/\n"
"QComboBox::down-arrow {\n"
"    image: url(:/ui/combobox_arrow.png);\n"
"}\n"
"QComboBox::down-arrow:hover {\n"
"    image: url(:/ui/combobox_arrow_2.png);\n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    image: url(:/ui/combobox_arrow_flip.png);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    /*border-left-width: 1px;*/\n"
"    border-left-color: rgb(200, 200, 220);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-radius: 8px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #efefef;\n"
"    background: #ffffff;\n"
"    border-radius: 8px;\n"
"    font-size: 16pt;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"    border-top: 2px solid #efefef;\n"
"    color: #0949ab;\n"
"    padding: 5px, 5px, 5px, 20px;\n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    color: #2fa43b;\n"
"}\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #ffffff, stop: 1 #dedede\n"
"    );\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/ui/checked.png);\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #5eb923, stop: 1 #279332\n"
"    );\n"
"}\n"
"\n"
"/* TABS */\n"
"QTabBar::tab {\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border: 1px solid #dedede;\n"
"border-bottom:  2px solid #dedede;\n"
"min-width: 60px;\n"
"padding: 5px 5px 0px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgb(250,250,250), stop: 1 #ffffff\n"
"    );\n"
"border-bottom:  1px solid #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"margin-top: 5px;\n"
"background: #eeeeee;\n"
"color:rgb(88, 99, 149);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"/*left: 10px;*/\n"
"top: 1px;\n"
"}\n"
"QTabWidget::pane {\n"
"border: 1px solid #eeeeee;\n"
"background: none;\n"
"border-radius: 10px;\n"
"border-top-left-radius: 0px;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.testButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(330, 450, 171, 50))
        self.testButton.setStyleSheet("")
        self.testButton.setObjectName("testButton")
        self.closeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(650, 10, 30, 30))
        self.closeButton.setStyleSheet("")
        self.closeButton.setObjectName("closeButton")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 455, 161, 40))
        self.comboBox.setObjectName("comboBox")
        self.minusButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(600, 10, 30, 30))
        self.minusButton.setStyleSheet("")
        self.minusButton.setObjectName("minusButton")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 431, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_wheel = QtWidgets.QWidget()
        self.tab_wheel.setObjectName("tab_wheel")
        self.wheelValueSlider = QtWidgets.QSlider(parent=self.tab_wheel)
        self.wheelValueSlider.setGeometry(QtCore.QRect(330, 19, 61, 251))
        self.wheelValueSlider.setMaximum(511)
        self.wheelValueSlider.setProperty("value", 511)
        self.wheelValueSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.wheelValueSlider.setObjectName("wheelValueSlider")
        self.tabWidget.addTab(self.tab_wheel, "")
        self.tab_hsv = QtWidgets.QWidget()
        self.tab_hsv.setObjectName("tab_hsv")
        self.lightnessSlider = QtWidgets.QSlider(parent=self.tab_hsv)
        self.lightnessSlider.setGeometry(QtCore.QRect(20, 220, 391, 50))
        self.lightnessSlider.setMaximum(100)
        self.lightnessSlider.setProperty("value", 0)
        self.lightnessSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lightnessSlider.setObjectName("lightnessSlider")
        self.saturationSlider = QtWidgets.QSlider(parent=self.tab_hsv)
        self.saturationSlider.setGeometry(QtCore.QRect(20, 130, 391, 50))
        self.saturationSlider.setMaximum(100)
        self.saturationSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.saturationSlider.setObjectName("saturationSlider")
        self.hueSlider = QtWidgets.QSlider(parent=self.tab_hsv)
        self.hueSlider.setGeometry(QtCore.QRect(20, 40, 391, 51))
        self.hueSlider.setMaximum(360)
        self.hueSlider.setProperty("value", 0)
        self.hueSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hueSlider.setObjectName("hueSlider")
        self.hueLabel = QtWidgets.QLabel(parent=self.tab_hsv)
        self.hueLabel.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.hueLabel.setObjectName("hueLabel")
        self.saturationLabel = QtWidgets.QLabel(parent=self.tab_hsv)
        self.saturationLabel.setGeometry(QtCore.QRect(20, 100, 221, 31))
        self.saturationLabel.setObjectName("saturationLabel")
        self.lightnessLabel = QtWidgets.QLabel(parent=self.tab_hsv)
        self.lightnessLabel.setGeometry(QtCore.QRect(20, 190, 221, 31))
        self.lightnessLabel.setObjectName("lightnessLabel")
        self.tabWidget.addTab(self.tab_hsv, "")
        self.tab_rgb = QtWidgets.QWidget()
        self.tab_rgb.setObjectName("tab_rgb")
        self.greenSlider = QtWidgets.QSlider(parent=self.tab_rgb)
        self.greenSlider.setGeometry(QtCore.QRect(20, 130, 391, 50))
        self.greenSlider.setMaximum(255)
        self.greenSlider.setProperty("value", 192)
        self.greenSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.greenSlider.setObjectName("greenSlider")
        self.blueLabel = QtWidgets.QLabel(parent=self.tab_rgb)
        self.blueLabel.setGeometry(QtCore.QRect(20, 190, 221, 31))
        self.blueLabel.setObjectName("blueLabel")
        self.redLabel = QtWidgets.QLabel(parent=self.tab_rgb)
        self.redLabel.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.redLabel.setObjectName("redLabel")
        self.greenLabel = QtWidgets.QLabel(parent=self.tab_rgb)
        self.greenLabel.setGeometry(QtCore.QRect(20, 100, 221, 31))
        self.greenLabel.setObjectName("greenLabel")
        self.redSlider = QtWidgets.QSlider(parent=self.tab_rgb)
        self.redSlider.setGeometry(QtCore.QRect(20, 40, 391, 50))
        self.redSlider.setMaximum(255)
        self.redSlider.setProperty("value", 0)
        self.redSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.redSlider.setObjectName("redSlider")
        self.blueSlider = QtWidgets.QSlider(parent=self.tab_rgb)
        self.blueSlider.setGeometry(QtCore.QRect(20, 220, 391, 50))
        self.blueSlider.setMaximum(255)
        self.blueSlider.setProperty("value", 0)
        self.blueSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.blueSlider.setObjectName("blueSlider")
        self.tabWidget.addTab(self.tab_rgb, "")
        self.testButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.testButton_2.setGeometry(QtCore.QRect(510, 450, 171, 50))
        self.testButton_2.setStyleSheet("")
        self.testButton_2.setObjectName("testButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 401, 51))
        self.label.setStyleSheet("font-size: 22pt;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 460, 71, 31))
        self.label_2.setStyleSheet("font-size: 22pt;")
        self.label_2.setObjectName("label_2")
        self.bottomBack = QtWidgets.QLabel(parent=self.centralwidget)
        self.bottomBack.setGeometry(QtCore.QRect(0, 434, 698, 81))
        self.bottomBack.setStyleSheet("background: qlineargradient(\n"
"    x1: 0, y1: 0, x2: 0, y2: 1,\n"
"    stop: 0 #b0b7c7, stop: 1 #cdd1dd\n"
");\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.bottomBack.setText("")
        self.bottomBack.setObjectName("bottomBack")
        self.refreshButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(260, 450, 50, 50))
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        self.refreshButton.setObjectName("refreshButton")
        self.bottomBack.raise_()
        self.tabWidget.raise_()
        self.testButton.raise_()
        self.closeButton.raise_()
        self.comboBox.raise_()
        self.minusButton.raise_()
        self.testButton_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.refreshButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USB Plumbob Color Picker"))
        self.testButton.setText(_translate("MainWindow", "Send"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wheel), _translate("MainWindow", "Wheel"))
        self.hueLabel.setText(_translate("MainWindow", "Hue"))
        self.saturationLabel.setText(_translate("MainWindow", "Saturation"))
        self.lightnessLabel.setText(_translate("MainWindow", "Lightness"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hsv), _translate("MainWindow", "HSL"))
        self.blueLabel.setText(_translate("MainWindow", "Blue"))
        self.redLabel.setText(_translate("MainWindow", "Red"))
        self.greenLabel.setText(_translate("MainWindow", "Green"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rgb), _translate("MainWindow", "RGB"))
        self.testButton_2.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "USB Plumbob Color Picker"))
        self.label_2.setText(_translate("MainWindow", "Port:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
